sudo: required
dist: trusty
language: node_js

services:
  - docker

node_js:
  - "8"

cache:
  directories:
  - node_modules

env:
  - DOCKER_COMPOSE_VERSION=1.21.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - npm run start_environment &
  - docker build -f Dockerfile.test -t dev-test-server-image . &
  - sleep 120
  - docker run -d dev-test-server-image --name dev-test-server-container
  - sleep 15
  - docker exec dev-test-server-container yarn run backend-test
  - npm run e2e-test