version: '3'
services:
    webapp:
        image: web
        build:
          context: .
          dockerfile: Dockerfile.web
        expose:
            - "8080"
            - "8443"
        ports:
            - "8080:8080"
            - "8443:8443"
        network_mode: "host"
    mongodb:
        image: mongo:3.6.2
        ports:
            - "27017:27017"
        volumes:
            - ./data/db:/data/db