version: '3'
services:
    webapp:
        image: ebuccaneer/waecm-2018-group-13-bsp-1-web
        expose:
            - "8080"
            - "8443"
        ports:
            - "8080:8080"
            - "8443:8443"
    mongodb:
        image: mongo:3.6.2
        ports:
            - "27017:27017"
        volumes:
            - ./data/db:/data/db